SLURM_VERSION?=22.05.9
PYTHON_VERSION?=3.9
SLURM_INCLUDE_DIR?=/usr/include/slurm
SLURM_PLUGIN_INSTALL_DIR?=/usr/lib64/slurm/
SLURM_SCRIPT_DIR?=/etc/slurm

SLURM_SRC_DIR=$(PWD)/slurm
SLURM_LIBRARY_FLAGS=-lslurmfull-$(SLURM_VERSION)
PYTHON_CONFIG?=python$(PYTHON_VERSION)-config
PYTHON_INCLUDE_FLAGS=$(shell $(PYTHON_CONFIG) --includes)
PYTHON_LIBRARY_FLAGS=$(shell $(PYTHON_CONFIG) --libs) -lpython$(PYTHON_VERSION)

CC=gcc
# CFLAGS=-g -O0
CFLAGS=-O3
CFLAGS+=-fPIC -Wall -std=c99 -Wfatal-errors -DDEFAULT_SCRIPT_DIR=\"$(SLURM_SCRIPT_DIR)\"

SOURCES=job_submit_python.c
OUTPUT_LIBRARY=job_submit_python.so
TEST_BINARY=job_submit_python.out

all: $(SOURCES) $(OUTPUT_LIBRARY)

$(OUTPUT_LIBRARY): $(SOURCES)
	$(CC) $(SOURCES) -o $@ -shared -I $(SLURM_INCLUDE_DIR) -I $(SLURM_SRC_DIR) $(PYTHON_INCLUDE_FLAGS) $(PYTHON_LIBRARY_FLAGS) $(SLURM_LIBRARY_FLAGS) $(CFLAGS)

$(TEST_BINARY): $(SOURCES)
	$(CC) $(SOURCES) -o $@ -I $(SLURM_INCLUDE_DIR) -I $(SLURM_SRC_DIR) $(PYTHON_INCLUDE_FLAGS) $(PYTHON_LIBRARY_FLAGS) $(SLURM_LIBRARY_FLAGS) $(CFLAGS)

clean:
	rm -f $(OUTPUT_LIBRARY) $(TEST_BINARY)

install: all
	install $(OUTPUT_LIBRARY) $(SLURM_PLUGIN_INSTALL_DIR)

test:
	tests/run_local.sh
